using System;

namespace Clearinet
{
    [Flags]
    public enum ExchangeFlags
    {
        None = 0,

        // Original URL was HTTPS
        IsHTTPS = 1,

        // Original URL was FTP
        IsFTP = 2,

        // Ignore this exchange. Don't raise events or store it.
        /// </summary>
        Ignored = 4,

        // Client pipe was reused.
        ClientPipeReused = 8,

        // Server pipe was reused.
        ServerPipeReused = 16,

        // Transmission to the server started before any body was read.
        RequestStreamed = 32,

        // Transmission to the client started before any body was read.
        ResponseStreamed = 64,

        // Exchange was generated by this tool.
        RequestGeneratedByClearinet = 128,

        // Response was generated by this tool
        ResponseGeneratedByClearinet = 256,

        // This exchange was loaded from a .SAZ File
        LoadedFromSAZ = 512,

        // This exchange was not from a SAZ or the proxy, e.g. a Transcoder
        ImportedFromOtherTool = 1024,

        // Request was sent to an upstream proxy
        SentToGateway = 2048,

        // Exchange established a CONNECT tunnel without decryption.
        IsBlindTunnel = 4096,

        // Exchange represents a CONNECT tunnel that was decrypted (e.g. HTTPS)
        IsDecryptingTunnel = 8192,

        // Response came from a cache (Set only during import from tools that log non-network requests)
        ServedFromCache = 16384,

        // Client's request violated the HTTP Protocol.
        ProtocolViolationInRequest = 32768,

        // Server's response violated the HTTP Protocol.
        ProtocolViolationInResponse = 0x10000,

        // Response body was dropped or never captured.
        ResponseBodyDropped = 0x20000,

        // This Exchange was used to tunnel WebSocket traffic.
        IsWebSocketTunnel = 0x40000,

        // This request was sent using the SOCKS protocol
        SentToSOCKSGateway = 0x80000,

        // Request body was dropped or never captured.
        RequestBodyDropped = 0x100000,

        // Exchange created an RPC tunnel (e.g. Outlook's RPC_OUT_DATA verb)
        IsRPCTunnel = 0x200000
    }

    // TODO: Consider whether we should add more states.
    public enum ExchangeStates : byte
    {
        Created,

        // Reading request from the client
        ReadingRequest,

        // Allowing extensions to tamper with the request
        AutoTamperRequestBefore,
        
        // Paused for manual tampering of the request
        HandTamperRequest,

        // Post-inspector tampering of the request
        AutoTamperRequestAfter,

        // Sending request to the server
        SendingRequest,

        // Reading response from the server
        ReadingResponse,

        // Pre-inspector tampering of the response
        AutoTamperResponseBefore,

        // Paused for manual tampering of the response
        HandTamperResponse,

        // Post-inspector tampering of the response
        AutoTamperResponseAfter,

        // Sending response to client application
        SendingResponse,

        // Exchange has completed processing
        Done,

        // Exchange was aborted due to an error or closed connection
        Aborted
    };
}
