<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <AssemblyName>CAE-$(MSBuildProjectName)</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Clearinet\Clearinet.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="powershell -Command &quot;$docPath = [Environment]::GetFolderPath('MyDocuments'); Copy-Item -Path '$(TargetPath)' -Destination \&quot;$docPath\Clearinet\Extensions\&quot; -Force&quot;" />
  </Target>

</Project>
